defmodule Moeda do
  @moduledoc """
  Este módulo possui listas com informações sobre as moedas.
  A lista está em compliance com o ISO 4217.
  Acesse https://pt.wikipedia.org/wiki/ISO_4217 para saber mais.
  """

  @doc """
  Lista as informações das moedas.

  ## Exemplo

  iex> IO.inspect(Moeda.info(), limit: :infinity)
  %{MGA: %{expoente: 2, nome: "Malagasy Ariary", simbolo: "Ar"},
    IRR: %{expoente: 2, nome: "Iranian Rial", simbolo: "﷼"},...

  """
  def info do
    moedas = [
      AED: %{nome: "UAE Dirham",                                             simbolo: "د.إ", expoente: 2},
      AFN: %{nome: "Afghani",                                                simbolo: "؋",    expoente: 2},
      ALL: %{nome: "Lek",                                                    simbolo: "Lek",  expoente: 2},
      AMD: %{nome: "Armenian Dram",                                          simbolo: "AMD",  expoente: 2},
      ANG: %{nome: "Netherlands Antillian Guilder",                          simbolo: "ƒ",    expoente: 2},
      AOA: %{nome: "Kwanza",                                                 simbolo: "Kz",   expoente: 2},
      ARS: %{nome: "Argentine Peso",                                         simbolo: "$",    expoente: 2},
      AUD: %{nome: "Australian Dollar",                                      simbolo: "$",    expoente: 2},
      AWG: %{nome: "Aruban Guilder",                                         simbolo: "ƒ",    expoente: 2},
      AZN: %{nome: "Azerbaijanian Manat",                                    simbolo: "ман",  expoente: 2},
      BAM: %{nome: "Convertible Marks",                                      simbolo: "KM",   expoente: 2},
      BBD: %{nome: "Barbados Dollar",                                        simbolo: "$",    expoente: 2},
      BDT: %{nome: "Taka",                                                   simbolo: "৳",     expoente: 2},
      BGN: %{nome: "Bulgarian Lev",                                          simbolo: "лв",   expoente: 2},
      BHD: %{nome: "Bahraini Dinar",                                         simbolo: ".د.ب", expoente: 3},
      BIF: %{nome: "Burundi Franc",                                          simbolo: "FBu",  expoente: 0},
      BMD: %{nome: "Bermudian Dollar (customarily known as Bermuda Dollar)", simbolo: "$",    expoente: 2},
      BND: %{nome: "Brunei Dollar",                                          simbolo: "$",    expoente: 2},
      BOB: %{nome: "Boliviano Mvdol",                                        simbolo: "$b",   expoente: 2},
      BOV: %{nome: "Boliviano Mvdol",                                        simbolo: "$b",   expoente: 2},
      BRL: %{nome: "Brazilian Real",                                         simbolo: "R$",   expoente: 2},
      BSD: %{nome: "Bahamian Dollar",                                        simbolo: "$",    expoente: 2},
      BTN: %{nome: "Indian Rupee Ngultrum",                                  simbolo: "Nu.",  expoente: 2},
      BWP: %{nome: "Pula",                                                   simbolo: "P",    expoente: 2},
      BYR: %{nome: "Belarussian Ruble",                                      simbolo: "p.",   expoente: 0},
      BZD: %{nome: "Belize Dollar",                                          simbolo: "BZ$",  expoente: 2},
      CAD: %{nome: "Canadian Dollar",                                        simbolo: "$",    expoente: 2},
      CDF: %{nome: "Congolese Franc",                                        simbolo: "CF",   expoente: 2},
      CHF: %{nome: "Swiss Franc",                                            simbolo: "CHF",  expoente: 2},
      CLF: %{nome: "Chilean Peso Unidades de fomento",                       simbolo: "$",    expoente: 4},
      CLP: %{nome: "Chilean Peso Unidades de fomento",                       simbolo: "$",    expoente: 0},
      CNY: %{nome: "Yuan Renminbi",                                          simbolo: "¥",    expoente: 2},
      COP: %{nome: "Colombian Peso",                                         simbolo: "$",    expoente: 2},
      COU: %{nome: "Colombian Peso Unidad de Valor Real",                    simbolo: "$",    expoente: 2},
      CRC: %{nome: "Costa Rican Colon",                                      simbolo: "₡",    expoente: 2},
      CUC: %{nome: "Cuban Peso Peso Convertible",                            simbolo: "₱",    expoente: 2},
      CUP: %{nome: "Cuban Peso Peso Convertible",                            simbolo: "₱",    expoente: 2},
      CVE: %{nome: "Cape Verde Escudo",                                      simbolo: "$",    expoente: 0},
      CZK: %{nome: "Czech Koruna",                                           simbolo: "Kč",   expoente: 2},
      DJF: %{nome: "Djibouti Franc",                                         simbolo: "Fdj",  expoente: 0},
      DKK: %{nome: "Danish Krone",                                           simbolo: "kr",   expoente: 2},
      DOP: %{nome: "Dominican Peso",                                         simbolo: "RD$",  expoente: 2},
      DZD: %{nome: "Algerian Dinar",                                         simbolo: "دج",   expoente: 2},
      EEK: %{nome: "Kroon",                                                  simbolo: "KR",   expoente: 2},
      EGP: %{nome: "Egyptian Pound",                                         simbolo: "£",    expoente: 2},
      ERN: %{nome: "Nakfa",                                                  simbolo: "Nfk",  expoente: 2},
      ETB: %{nome: "Ethiopian Birr",                                         simbolo: "Br",   expoente: 2},
      EUR: %{nome: "Euro",                                                   simbolo: "€",    expoente: 2},
      FJD: %{nome: "Fiji Dollar",                                            simbolo: "$",    expoente: 2},
      FKP: %{nome: "Falkland Islands Pound",                                 simbolo: "£",    expoente: 2},
      GBP: %{nome: "Pound Sterling",                                         simbolo: "£",    expoente: 2},
      GEL: %{nome: "Lari",                                                   simbolo: "₾",    expoente: 2},
      GHS: %{nome: "Cedi",                                                   simbolo: "GH₵",  expoente: 2},
      GIP: %{nome: "Gibraltar Pound",                                        simbolo: "£",    expoente: 2},
      GMD: %{nome: "Dalasi",                                                 simbolo: "D",    expoente: 2},
      GNF: %{nome: "Guinea Franc",                                           simbolo: "FG",   expoente: 0},
      GTQ: %{nome: "Quetzal",                                                simbolo: "Q",    expoente: 2},
      GYD: %{nome: "Guyana Dollar",                                          simbolo: "$",    expoente: 2},
      HKD: %{nome: "Hong Kong Dollar",                                       simbolo: "$",    expoente: 2},
      HNL: %{nome: "Lempira",                                                simbolo: "L",    expoente: 2},
      HRK: %{nome: "Croatian Kuna",                                          simbolo: "kn",   expoente: 2},
      HTG: %{nome: "Gourde US Dollar",                                       simbolo: " ",    expoente: 2},
      HUF: %{nome: "Forint",                                                 simbolo: "Ft",   expoente: 2},
      IDR: %{nome: "Rupiah",                                                 simbolo: "Rp",   expoente: 2},
      ILS: %{nome: "New Israeli Sheqel",                                     simbolo: "₪",    expoente: 2},
      INR: %{nome: "Indian Rupee",                                           simbolo: "₹",    expoente: 2},
      IQD: %{nome: "Iraqi Dinar",                                            simbolo: "‎ع.د",  expoente: 3},
      IRR: %{nome: "Iranian Rial",                                           simbolo: "﷼",   expoente: 2},
      ISK: %{nome: "Iceland Krona",                                          simbolo: "kr",   expoente: 0},
      JMD: %{nome: "Jamaican Dollar",                                        simbolo: "J$",   expoente: 2},
      JOD: %{nome: "Jordanian Dinar",                                        simbolo: "JOD",  expoente: 3},
      JPY: %{nome: "Yen",                                                    simbolo: "¥",    expoente: 0},
      KES: %{nome: "Kenyan Shilling",                                        simbolo: "KSh",  expoente: 2},
      KGS: %{nome: "Som",                                                    simbolo: "лв",   expoente: 2},
      KHR: %{nome: "Riel",                                                   simbolo: "៛",     expoente: 2},
      KMF: %{nome: "Comoro Franc",                                           simbolo: "CF",   expoente: 0},
      KPW: %{nome: "North Korean Won",                                       simbolo: "₩",    expoente: 2},
      KRW: %{nome: "Won",                                                    simbolo: "₩",    expoente: 0},
      KWD: %{nome: "Kuwaiti Dinar",                                          simbolo: "د.ك",  expoente: 3},
      KYD: %{nome: "Cayman Islands Dollar",                                  simbolo: "$",    expoente: 2},
      KZT: %{nome: "Tenge",                                                  simbolo: "лв",   expoente: 2},
      LAK: %{nome: "Kip",                                                    simbolo: "₭",    expoente: 2},
      LBP: %{nome: "Lebanese Pound",                                         simbolo: "£",    expoente: 2},
      LKR: %{nome: "Sri Lanka Rupee",                                        simbolo: "₨",    expoente: 2},
      LRD: %{nome: "Liberian Dollar",                                        simbolo: "$",    expoente: 2},
      LSL: %{nome: "Rand Loti",                                              simbolo: " ",    expoente: 2},
      LTL: %{nome: "Lithuanian Litas",                                       simbolo: "Lt",   expoente: 2},
      LVL: %{nome: "Latvian Lats",                                           simbolo: "Ls",   expoente: 2},
      LYD: %{nome: "Libyan Dinar",                                           simbolo: "ل.د",  expoente: 3},
      MAD: %{nome: "Moroccan Dirham",                                        simbolo: "د.م.", expoente: 2},
      MDL: %{nome: "Moldovan Leu",                                           simbolo: "MDL",  expoente: 2},
      MGA: %{nome: "Malagasy Ariary",                                        simbolo: "Ar",   expoente: 2},
      MKD: %{nome: "Denar",                                                  simbolo: "ден",  expoente: 2},
      MMK: %{nome: "Kyat",                                                   simbolo: "K",    expoente: 2},
      MNT: %{nome: "Tugrik",                                                 simbolo: "₮",    expoente: 2},
      MOP: %{nome: "Pataca",                                                 simbolo: "MOP$", expoente: 2},
      MRO: %{nome: "Ouguiya",                                                simbolo: "UM",   expoente: 2},
      MUR: %{nome: "Mauritius Rupee",                                        simbolo: "₨",    expoente: 2},
      MVR: %{nome: "Rufiyaa",                                                simbolo: "Rf",   expoente: 2},
      MWK: %{nome: "Kwacha",                                                 simbolo: "MK",   expoente: 2},
      MXN: %{nome: "Mexican Peso",                                           simbolo: "$",    expoente: 2},
      MXV: %{nome: "Mexican Peso Mexican Unidad de Inversion (UDI)",         simbolo: "UDI",  expoente: 2},
      MYR: %{nome: "Malaysian Ringgit",                                      simbolo: "RM",   expoente: 2},
      MZN: %{nome: "Metical",                                                simbolo: "MT",   expoente: 2},
      NAD: %{nome: "Rand Namibia Dollar",                                    simbolo: "$",    expoente: 2},
      NGN: %{nome: "Naira",                                                  simbolo: "₦",    expoente: 2},
      NIO: %{nome: "Cordoba Oro",                                            simbolo: "C$",   expoente: 2},
      NOK: %{nome: "Norwegian Krone",                                        simbolo: "kr",   expoente: 2},
      NPR: %{nome: "Nepalese Rupee",                                         simbolo: "₨",    expoente: 2},
      NZD: %{nome: "New Zealand Dollar",                                     simbolo: "$",    expoente: 2},
      OMR: %{nome: "Rial Omani",                                             simbolo: "﷼",   expoente: 3},
      PAB: %{nome: "Balboa US Dollar",                                       simbolo: "B/.",  expoente: 2},
      PEN: %{nome: "Nuevo Sol",                                              simbolo: "S/.",  expoente: 2},
      PGK: %{nome: "Kina",                                                   simbolo: "K",    expoente: 2},
      PHP: %{nome: "Philippine Peso",                                        simbolo: "Php",  expoente: 2},
      PKR: %{nome: "Pakistan Rupee",                                         simbolo: "₨",    expoente: 2},
      PLN: %{nome: "Zloty",                                                  simbolo: "zł",   expoente: 2},
      PYG: %{nome: "Guarani",                                                simbolo: "Gs",   expoente: 0},
      QAR: %{nome: "Qatari Rial",                                            simbolo: "﷼",   expoente: 2},
      RON: %{nome: "New Leu",                                                simbolo: "lei",  expoente: 2},
      RSD: %{nome: "Serbian Dinar",                                          simbolo: "Дин.", expoente: 2},
      RUB: %{nome: "Russian Ruble",                                          simbolo: "₽",    expoente: 2},
      RWF: %{nome: "Rwanda Franc",                                           simbolo: " ",    expoente: 0},
      SAR: %{nome: "Saudi Riyal",                                            simbolo: "﷼",   expoente: 2},
      SBD: %{nome: "Solomon Islands Dollar",                                 simbolo: "$",    expoente: 2},
      SCR: %{nome: "Seychelles Rupee",                                       simbolo: "₨",    expoente: 2},
      SDG: %{nome: "Sudanese Pound",                                         simbolo: "SDG",  expoente: 2},
      SEK: %{nome: "Swedish Krona",                                          simbolo: "kr",   expoente: 2},
      SGD: %{nome: "Singapore Dollar",                                       simbolo: "$",    expoente: 2},
      SHP: %{nome: "Saint Helena Pound",                                     simbolo: "£",    expoente: 2},
      SLL: %{nome: "Leone",                                                  simbolo: "Le",   expoente: 2},
      SOS: %{nome: "Somali Shilling",                                        simbolo: "S",    expoente: 2},
      SRD: %{nome: "Surinam Dollar",                                         simbolo: "$",    expoente: 2},
      STD: %{nome: "Dobra",                                                  simbolo: "Db",   expoente: 2},
      SVC: %{nome: "El Salvador Colon US Dollar",                            simbolo: "$",    expoente: 2},
      SYP: %{nome: "Syrian Pound",                                           simbolo: "£",    expoente: 2},
      SZL: %{nome: "Lilangeni",                                              simbolo: "E",    expoente: 2},
      THB: %{nome: "Baht",                                                   simbolo: "฿",    expoente: 2},
      TJS: %{nome: "Somoni",                                                 simbolo: " ",    expoente: 2},
      TMT: %{nome: "Manat",                                                  simbolo: "₼",    expoente: 2},
      TND: %{nome: "Tunisian Dinar",                                         simbolo: "د.ت",  expoente: 2},
      TOP: %{nome: "Pa'anga",                                                simbolo: "T$",   expoente: 2},
      TRY: %{nome: "Turkish Lira",                                           simbolo: "TL",   expoente: 2},
      TTD: %{nome: "Trinidad and Tobago Dollar",                             simbolo: "TT$",  expoente: 2},
      TWD: %{nome: "New Taiwan Dollar",                                      simbolo: "NT$",  expoente: 2},
      TZS: %{nome: "Tanzanian Shilling",                                     simbolo: "Tsh",  expoente: 2},
      UAH: %{nome: "Hryvnia",                                                simbolo: "₴",    expoente: 2},
      UGX: %{nome: "Uganda Shilling",                                        simbolo: "Ush",  expoente: 0},
      USD: %{nome: "US Dollar",                                              simbolo: "$",    expoente: 2},
      UYI: %{nome: "Peso Uruguayo Uruguay Peso en Unidades Indexadas",       simbolo: "$U",   expoente: 0},
      UYU: %{nome: "Peso Uruguayo Uruguay Peso en Unidades Indexadas",       simbolo: "$U",   expoente: 2},
      UZS: %{nome: "Uzbekistan Sum",                                         simbolo: "лв",   expoente: 2},
      VEF: %{nome: "Bolivar Fuerte",                                         simbolo: "Bs",   expoente: 2},
      VND: %{nome: "Dong",                                                   simbolo: "₫",    expoente: 0},
      VUV: %{nome: "Vatu",                                                   simbolo: "VT",   expoente: 0},
      WST: %{nome: "Tala",                                                   simbolo: "WS$",  expoente: 2},
      XAF: %{nome: "CFA Franc BEAC",                                         simbolo: "FCFA", expoente: 0},
      XAG: %{nome: "Silver",                                                 simbolo: " ",    expoente: 2},
      XAU: %{nome: "Gold",                                                   simbolo: " ",    expoente: 2},
      XBA: %{nome: "Bond Markets Units European Composite Unit (EURCO)",     simbolo: " ",    expoente: 2},
      XBB: %{nome: "European Monetary Unit (E.M.U.-6)",                      simbolo: " ",    expoente: 2},
      XBC: %{nome: "European Unit of Account 9(E.U.A.-9)",                   simbolo: " ",    expoente: 2},
      XBD: %{nome: "European Unit of Account 17(E.U.A.-17)",                 simbolo: " ",    expoente: 2},
      XCD: %{nome: "East Caribbean Dollar",                                  simbolo: "$",    expoente: 2},
      XDR: %{nome: "SDR",                                                    simbolo: " ",    expoente: 2},
      XFU: %{nome: "UIC-Franc",                                              simbolo: " ",    expoente: 2},
      XOF: %{nome: "CFA Franc BCEAO",                                        simbolo: " ",    expoente: 0},
      XPD: %{nome: "Palladium",                                              simbolo: " ",    expoente: 2},
      XPF: %{nome: "CFP Franc",                                              simbolo: " ",    expoente: 0},
      XPT: %{nome: "Platinum",                                               simbolo: " ",    expoente: 2},
      XTS: %{nome: "Codes specifically reserved for testing purposes",       simbolo: " ",    expoente: 2},
      YER: %{nome: "Yemeni Rial",                                            simbolo: "﷼",   expoente: 2},
      ZAR: %{nome: "Rand",                                                   simbolo: "R",    expoente: 2},
      ZMK: %{nome: "Zambian Kwacha",                                         simbolo: "ZK",   expoente: 2},
      ZWL: %{nome: "Zimbabwe Dollar",                                        simbolo: "$",    expoente: 2}    
    ]
  end 
  @doc """
  Lista com as moedas para a criação de novos usuários no sistema.

  Todas moedas começam com valor 0

  ## Exemplo

  iex> usuario[Pedro: Moeda.novo()]
  [AED: 0, AFN: 0, ALL: 0, AMD: 0, ANG: 0, AOA: 0, ARS: 0, AUD: 0, AWG: 0, AZN: 0,
   BAM: 0, BBD: 0, BDT: 0, BGN: 0, BHD: 0, BIF: 0, BMD: 0, BND: 0, BOB: 0, BOV: 0,...
  
  """
  def novo do
    novo = [
      AED: 0, 
      AFN: 0,
      ALL: 0,
      AMD: 0,
      ANG: 0,
      AOA: 0,
      ARS: 0,
      AUD: 0,
      AWG: 0,
      AZN: 0, 
      BAM: 0,
      BBD: 0,
      BDT: 0,
      BGN: 0,
      BHD: 0,
      BIF: 0,
      BMD: 0,
      BND: 0,
      BOB: 0,
      BOV: 0,
      BRL: 0,
      BSD: 0,
      BTN: 0,
      BWP: 0,
      BYR: 0,
      BZD: 0,
      CAD: 0,
      CDF: 0,
      CHF: 0,
      CLF: 0,
      CLP: 0,
      CNY: 0,
      COP: 0,
      COU: 0,
      CRC: 0,
      CUC: 0,
      CUP: 0,
      CVE: 0,
      CZK: 0,
      DJF: 0,
      DKK: 0,
      DOP: 0,
      DZD: 0,
      EEK: 0,
      EGP: 0,
      ERN: 0,
      ETB: 0,
      EUR: 0,
      FJD: 0,
      FKP: 0,
      GBP: 0,
      GEL: 0,
      GHS: 0,
      GIP: 0,
      GMD: 0,
      GNF: 0,
      GTQ: 0,
      GYD: 0,
      HKD: 0,
      HNL: 0,
      HRK: 0,
      HTG: 0,
      HUF: 0,
      IDR: 0,
      ILS: 0,
      INR: 0,
      IQD: 0,
      IRR: 0,
      ISK: 0,
      JMD: 0,
      JOD: 0,
      JPY: 0,
      KES: 0,
      KGS: 0,
      KHR: 0,
      KMF: 0,
      KPW: 0,
      KRW: 0,
      KWD: 0,
      KYD: 0,
      KZT: 0,
      LAK: 0,
      LBP: 0,
      LKR: 0,
      LRD: 0,
      LSL: 0,
      LTL: 0,
      LVL: 0,
      LYD: 0,
      MAD: 0,
      MDL: 0,
      MGA: 0,
      MKD: 0,
      MMK: 0,
      MNT: 0,
      MOP: 0,
      MRO: 0,
      MUR: 0,
      MVR: 0,
      MWK: 0,
      MXN: 0,
      MXV: 0,
      MYR: 0,
      MZN: 0,
      NAD: 0,
      NGN: 0,
      NIO: 0,
      NOK: 0,
      NPR: 0,
      NZD: 0,
      OMR: 0,
      PAB: 0,
      PEN: 0,
      PGK: 0,
      PHP: 0,
      PKR: 0,
      PLN: 0,
      PYG: 0,
      QAR: 0,
      RON: 0,
      RSD: 0,
      RUB: 0,
      RWF: 0,
      SAR: 0,
      SBD: 0,
      SCR: 0,
      SDG: 0,
      SEK: 0,
      SGD: 0,
      SHP: 0,
      SLL: 0,
      SOS: 0,
      SRD: 0,
      STD: 0,
      SVC: 0,
      SYP: 0,
      SZL: 0,
      THB: 0,
      TJS: 0,
      TMT: 0,
      TND: 0,
      TOP: 0,
      TRY: 0,
      TTD: 0,
      TWD: 0,
      TZS: 0,
      UAH: 0,
      UGX: 0,
      USD: 0,
      UYI: 0,
      UYU: 0,
      UZS: 0,
      VEF: 0,
      VND: 0,
      VUV: 0,
      WST: 0,
      XAF: 0,
      XAG: 0,
      XAU: 0,
      XBA: 0,
      XBB: 0,
      XBC: 0,
      XBD: 0,
      XCD: 0,
      XDR: 0,
      XFU: 0,
      XOF: 0,
      XPD: 0,
      XPF: 0,
      XPT: 0,
      XTS: 0,
      YER: 0,
      ZAR: 0,
      ZMK: 0,
      ZWL: 0
    ]
  end
end